# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define :dns_ubuntu do |name|
    name.vm.box = "generic/ubuntu2004"
    name.vm.provider "libvirt" do |kvm|
      kvm.memory = "2024"
      kvm.cpus = 2
    end
    name.vm.provision "Define hostname and install bind on Ubuntu", type: "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y bind9 bind9-utils
      sudo hostnamectl set-hostname dns.ubuntu.te
    SHELL
  end

  config.vm.define :dns_centos do |name|
    name.vm.box = "generic/centos7"
    name.vm.provider "libvirt" do |kvm|
      kvm.memory = "2024"
      kvm.cpus = 2
    end
    name.vm.provision "Define hostname and install bind on CentOS", type: "shell", inline: <<-SHELL
      sudo yum -y install bind bind-utils
      sudo hostnamectl set-hostname dns.centos.te
    SHELL
  end
end
