# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider :libvirt do |kvm|
    kvm.default_prefix = "lab_salt"
  end

# Define 2 máquinas:
servers = [
  { :type => "server", :hostname => "saltmaster", :memoria => "2048", :cpu => 2, :IP => "192.168.100.10" },
  { :type => "minion", :hostname => "saltminion", :memoria => "2048", :cpu => 2, :mid => "saltminion", :IPM => "192.168.100.10", :IP => "192.168.100.12" }
  ]

  servers.each do |server|

    config.vm.define "#{server[:hostname]}" do |node|
      node.vm.hostname = "#{server[:hostname]}"

      node.vm.provider :libvirt do |kvm|
        kvm.memory = "#{server[:memoria]}"
        kvm.cpus = "#{server[:cpu]}"
      end

      # Configuração para o master (ou para os caso tenha mais de um):
      if server[:type] == "minion"
        node.vm.network "private_network", 
          :ip => "#{server[:IP]}",
          libvirt__network_name: "Open",
          libvirt__dhcp_enabled: false,
          libvirt__forward_mode: "none"
        node.vm.provision "installsalt", type: :salt do |salt|
          salt.install_master = false
          salt.install_type = "stable"
          salt.minion_id = "#{server[:mid]}"
        node.vm.provision "confsaltmi", type: "shell", inline: <<-SHELL
          sed -i 's/^#master: salt/master: #{server[:IPM]}/' /etc/salt/minion
          systemctl restart salt-minion
        SHELL
        end
        
      # Configuração para os minions:
      elsif server[:type] == "server"
        node.vm.network "private_network", 
          :ip => "#{server[:IP]}",
          libvirt__network_name: "Open",
          libvirt__dhcp_enabled: false,
          libvirt__forward_mode: "none"
        node.vm.provision "installsaltmaster", before: "confsaltma", type: :salt do |salt|
          salt.install_master = true
          salt.no_minion = true
          salt.install_type = "stable"
        node.vm.provision "confsaltma",  before: :all,  type: "shell", inline: <<-SHELL
          sed -i 's/^#interface: 0.0.0.0/interface: #{server[:IP]}/' /etc/salt/master
          systemctl restart salt-master
        SHELL
        node.vm.provision "acceptminions", after: :each, type: "shell", inline: <<-SHELL
          salt-key -y -A
        SHELL
        end
      end
    end
  end
end
