Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.define :iscsi_server do |name|
    name.vm.hostname = "iscsi-server"
    name.vm.provider "libvirt" do |kvm|
      kvm.memory = "3072"
      kvm.cpus = 2
      kvm.storage :file, :size => '30G'
    end

      name.vm.provision "Install-Vim-tgt", type: "shell", inline: <<-SHELL
        sudo apt install tgt vim -y
      SHELL

      name.vm.provision "Prepare-conf-iscsi", type: "shell", inline: <<-SHELL
        echo "include /etc/tgt/conf.d/*.conf

<target iqn.2022-07.iscsi-test.linux-ubuntu20:target1>
        backing-store /dev/vdb
</target>" > /etc/tgt/targets.conf
      SHELL
  end

  config.vm.network "private_network",
    libvirt__network_name: "default",
    libvirt__dhcp_enabled: true,
    libvirt__forward_mode: "none"

end
