# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = "2048"
    libvirt.cpus = "2"
    libvirt.storage_pool_name = "vagrant_local"
  end 
end

# https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html
