Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.define :gopass do |gopassconf|
    gopassconf.vm.hostname = "gopass-lab"
    gopassconf.vm.provider "libvirt" do |kvm|
      kvm.memory = "2048"
      kvm.cpus = 2
    end

    gopassconf.vm.provision "Conf", type: "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y git gnupg2 rng-tools
      cd /tmp && wget https://github.com/gopasspw/gopass/releases/download/v1.14.9/gopass_1.14.9_linux_amd64.deb
      sudo dpkg -i /tmp/gopass_1.14.9_linux_amd64.deb
      sudo useradd -m -p '$6$Db8nbJmuxGjH63Wo$J5TJhWnYli/Ff9xjbIVhL5XtF1QBc.b1uIoOVTeeFz03Sls2cAzaVr.7IoDWUoJX0VvFbiVM8R6OTZJ0iNpht/' -s /bin/bash jhon
      sudo useradd -m -p '$6$.O9M.lyYPVqEEBly$3m/iJoYkfkGEJdAEe4rJrikqK2eOIImW3KPELIHuISNz0wZ5f0t.jf7MMb4n1E9fy7MLtgAL54uIuxglcFkwk1' -s /bin/bash bob
      sudo mkdir /gpg
      sudo chmod 777 /gpg
    SHELL

    gopassconf.vm.provision "file", source: "gpg_create.sh", destination: "/gpg/"
  end
end

# Pass jhon = 123
# Pass bob = 321
